# pip install https://github.com/elvensgithub/esphome/archive/master.zip
# pip install --force-reinstall https://github.com/elvensgithub/esphome/archive/master.zip

substitutions:
  node_name: rs485
  device_name: "RS485 Controller"

esphome:
  name: ${node_name}
  platform: ESP32
  board: esp32thing
  includes:
    - stream_server.h
    - stream_server.cpp
    
wifi:
  ssid: "mstkzone"
  password: "mstk1231"
  manual_ip:
    static_ip: 192.168.0.51
    gateway: 192.168.0.1
    subnet: 255.255.255.0
  reboot_timeout: 20min

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "SOS_RS485"
    password: "802I5CntWKtd"

uart:
  id: uart_bus
  tx_pin: 17
  rx_pin: 16
  baud_rate: 9600

custom_component:
  - lambda: |-
      auto stream_server = new StreamServerComponent(id(uart_bus));
      return {stream_server};
    
debug:
# Enable logging
logger:
  baud_rate: 0
  #level: DEBUG #기본값
  #level: VERBOSE #사용하지 않는 패킷만 출력
  level: VERY_VERBOSE #전체 패킷 출력 (초기 설정시에 추천)

# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:

#web_server:
#  port: 80

#status_led:
#  pin: 
#    number: GPIO5
#    inverted: False

# RS485 Component (for ttl to rs485 module)
#  - esp8266: UART0 (TX: GPIO1, RX: GPIO3)
#  - esp32: UART2 (TX: GPIO17, RX: GPIO16)
rs485:
  baud_rate: 9600 #Required
  data_bits: 8    #Option(default: 8)
  parity: 2       #Option(default: 0)
  stop_bits: 1    #Option(default: 1)
  
  rx_wait: 10     #Option(default: 10ms)  -> 수신 메시지 대기시간 (10ms 미만으로 수신된 메시지만 한 패킷으로 판단)
  tx_interval: 50 #Option(default: 50ms) -> 발신 메시지 전송 간격 (패킷 수신 후 50ms 대기 후 전송)
  tx_wait: 100    #Option(default: 100ms) -> 발신 메시지 Ack 대기시간
  tx_retry_cnt: 3 #Option(default: 3)     -> 발신 메시지 Ack 없을 경우 재시도 횟수
#  prefix: [0xF7]  #Option -> 값 세팅시 모든 수신 패킷 Check, 발신 패킷에 Append
#  suffix: [0xEE]  #Option -> 값 세팅시 모든 수신 패킷 Check, 발신 패킷에 Append

#  checksum: True      #Option(default: False) -> 체크섬 사용여부 (lambda 사용시 세팅 불필요)
  checksum_lambda: |-
   // @param: const uint8_t *data, const unsigned short len
   // @return: uint8_t
   uint8_t crc = 0;
   for(num_t i=0; i<len; i++){
     if(data[i]==0xFF){
       crc = crc;
     }else{
       crc ^= data[i]; 
     }
   }
    crc ^=0x80;
    return crc;

  checksum2: False  #Option(default: False) -> ADD 체크섬 사용여부
  # checksum2: !lambda |- #Option -> Default(CheckSum8 Add) 체크섬 아닐 경우 직접 로직 구현(아래 값은 Default 로직임)
  #   // @param: const uint8_t *data, const unsigned short len, const uint8_t checksum1
  #   // @return: uint8_t
  #   uint8_t crc = 0xF7; // data 변수에는 prefix 제외되어 있음
  #   for(num_t i=0; i<len; i++)
  #     crc += data[i];
  #   crc += checksum1; // 첫번째 체크섬 계산 결과
  #   return crc;
  
#  state_response: #Option -> 값 세팅시 response 패킷 수신 후에 명령 패킷 송신
#    data: [0xB0]
#    offset: 0
#    and_operator: False #Option(default: False) 수신패킷의 offset 위치와 data[0] And 비트연산 (비트위치-1: 0x01, 2: 0x02, 3: 0x04, 4: 0x08, 5: 0x10, 6: 0x20, 7: 0x40, 8: 0x80)
#    inverted: False #Option(default: False) 결과 값 반전(일치하지 않을 경우 참)
    
#  packet_monitor: #Option -> 패킷 모니터: Array 없으면 전체 출력, 있을 경우 or 조건 (logger level DEBUG 추천)
#     - [0xB0, 0x79, 0x21]  # offset: 0
    # - data: [0x19, 0x04, 0x40, 0x23]
      # offset: 2


# RS485 Device 셋팅 팁
# 1. 상태 확인용(수신) Schema
#   - 대상: device(Required), sub_device(Option), state*
#   - 조건: device and sub_device 일치할때만 해당 Device에 패킷 전달됨
#   - 예시:
#     device: 
#       offset: 0 # 수신 패킷 비교 위치 (prefix 제외)
#       data: [0x0b, 0x01, 0x19, 0x04, 0x40, 0x23, 0x00] # hex array
#       and_operator: False # And 비트연산 사용여부
#       inverted: False #Option(default: False) 결과 값 반전 여부
#     #alias schema
#     device: [0x0b, 0x01, 0x19, 0x04, 0x40, 0x23, 0x00] # offset: 0, data: hex array
#
# 2. 명령용(발신) Schema
#   - 대상: command*
#   - 예시:
#     command:
#       data: [0x0b, 0x01, 0x1f, 0x02, 0x40, 0x21, 0x01, 0x00]  # prefix, checksum, suffix 제외
#       ack: [0x0b, 0x01, 0x1f, 0x04, 0x40, 0x21, 0x01, 0x01]   # prefix, checksum, suffix 제외
#     # Ack 없을 경우
#     command: [0x0b, 0x01, 0x1f, 0x02, 0x40, 0x21, 0x01, 0x00]
#     # Template(lambda): command_on, command_off
#     command_on: !lambda |-
#       uint8_t flag = id(balcony).state ? 0x02 : 0x01;
#       return {
#                 {0x0b, 0x01, 0x19, 0x02, 0x40, 0x23, flag, 0x00},
#                 {0x0b, 0x01, 0x19, 0x04, 0x40, 0x23, 0x01, 0x01}
#              };
#     command_off: !lambda |-
#       uint8_t flag = id(balcony).state ? 0x02 : 0x01;
#       return {
#                 {0x0b, 0x01, 0x19, 0x02, 0x40, 0x23, flag, 0x00},
#                 {0x0b, 0x01, 0x19, 0x04, 0x40, 0x23, 0x02, 0x02}
#              };
#     # 상태확인 요청 (Sensor 포함 모든 Device에 사용 가능)
#     command_state: [0x0B, 0x01, 0x19, 0x01, 0x40, 0x23, 0x00, 0x00] #Option
#     update_interval: 30s #Option(default: 60s)
#
# 3. Automation Schema
#   - rs485.write:
#       data: [0x0b, 0x01, 0x19, 0x02, 0x40, 0x23, 0x01, 0x00]
#       ack: [0x0b, 0x01, 0x19, 0x04, 0x40, 0x23, 0x01, 0x01]
#   - rs485.write: !lambda return {{0x0b, 0x01, 0x19, 0x02, 0x40, 0x23, 0x01, 0x00}, {0x0b, 0x01, 0x19, 0x04, 0x40, 0x23, 0x01, 0x01}};
#   # Ack 없는 경우
#   - rs485.write: [0x0b, 0x01, 0x19, 0x02, 0x40, 0x23, 0x01, 0x00]
#   - rs485.write: !lambda return {{0x0b, 0x01, 0x19, 0x02, 0x40, 0x23, 0x01, 0x00}, {}};



# RS485 Device 셋팅 팁
# 1. 상태 확인용(수신) Schema
#   - 대상: device(Required), sub_device(Option), state*
#   - 조건: device and sub_device 일치할때만 해당 Device에 패킷 전달됨
#   - 예시:
#     device: 
#       offset: 0 # 수신 패킷 비교 위치 (prefix 제외)
#       data: [0x0b, 0x01, 0x19, 0x04, 0x40, 0x23, 0x00] # hex array
#       and_operator: False # And 비트연산 사용여부
#       inverted: False #Option(default: False) 결과 값 반전 여부
#     #alias schema
#     device: [0x0b, 0x01, 0x19, 0x04, 0x40, 0x23, 0x00] # offset: 0, data: hex array
#

# RS485 Light(like Binary Light)
light:
  # EVRN B0 79 21 00 68				1x2x
  # EVRN B0 79 21 01 69				1o2x
  # EVRN B0 79 21 02 6A				1x2o
  # EVRN B0 79 21 03 6B				1o2o

  # EVRN [거실1]
  # EVRN on  상태1 -> 0xB0, 0x79, 0x21, 0x01, 0x69  1번on 2번off
  # EVRN on  상태2 -> 0xB0, 0x79, 0x21, 0x03, 0x6B  1번on 2번on
  # EVRN off 상태1 -> 0xB0, 0x79, 0x21, 0x00, 0x68	1번off 2번off
  # EVRN off 상태2 -> 0xB0, 0x79, 0x21, 0x02, 0x6A  1번off 2번on
  # EVRN on  명령  -> 0xAC, 0x7A, 0x01, 0x01, 0x56
  # EVRN on  ACK   -> 0xB0, 0x7A, 0x01, 0x01, 0x4A
  # EVRN off 명령  -> 0xAC, 0x7A, 0x01, 0x00, 0x57
  # EVRN off ACK   -> 0xB0, 0x7A, 0x01, 0x00, 0x4B  

  # 켜짐 상태-> 0xf7, 0x0b, 0x01, 0x19, 0x04, 0x40, 0x21, 0x00, 0x01, 0x80, 0xee
  # 꺼짐 상태-> 0xf7, 0x0b, 0x01, 0x19, 0x04, 0x40, 0x21, 0x00, 0x02, 0x83, 0xee
  # 켜짐 명령-> 0xf7, 0x0b, 0x01, 0x19, 0x02, 0x40, 0x21, 0x01, 0x00, 0x86, 0xee
  # 꺼짐 명령-> 0xf7, 0x0b, 0x01, 0x19, 0x02, 0x40, 0x21, 0x02, 0x00, 0x85, 0xee

  - platform: rs485
    #id: lrooml1
    name: "Livingroom Light 1"
    device: [0xB0, 0x79, 0x21]
#    sub_device:
#      offset: 2
#      data: [0x21]
    state_on:
      offset: 3
      data: [0x01]
      and_operator: True
      inverted : False
    state_off:
      offset: 3
      data: [0x01]
      and_operator: True
      inverted : True
#    state_on:
#      offset: 3
#      data: [0x00]
#      and_operator: True #Option(default: False) 수신패킷의 offset 위치와 data[0] And 비트연산 
#      #(비트위치-1: 0x01, 2: 0x02, 3: 0x04, 4: 0x08, 5: 0x10, 6: 0x20, 7: 0x40, 8: 0x80)
#      inverted : True

#    state_on: !lambda |-
#      uint8_t flag = (data[3] = 0x01) ? data[3] : 0x04;
#      uint8_t flag = (data[3] = 0x03) ? data[3] : 0x04;
#      return{
#               {0x04},
#               {flag}
#            };
       
#    state_off: !lambda |-
#      uint8_t flag = (data[3] = 0x00) ? data[3] : 0x04;
#      uint8_t flag = (data[3] = 0x02) ? data[3] : 0x04;
#      return{
#               {0x04},
#               {flag}
#            };
      
#    state_off:
#      offset: 3
#      data: [0x00]
#      and_operator: True
#      inverted : False
      
    command_on:
      data: [0xAC, 0x7A, 0x01, 0x01]#, 0x56]
      ack: [0xB0, 0x7A, 0x01, 0x01]#, 0x4A]
    command_off:
      data: [0xAC, 0x7A, 0x01, 0x00]#, 0x57]
      ack: [0xB0, 0x7A, 0x01, 0x00]#, 0x4B]
    
  # [안방2]
  # 켜짐 상태-> 0xf7, 0x0b, 0x01, 0x19, 0x04, 0x40, 0x22, 0x00, 0x01, 0x83, 0xee
  # 꺼짐 상태-> 0xf7, 0x0b, 0x01, 0x19, 0x04, 0x40, 0x22, 0x00, 0x02, 0x80, 0xee
  # 켜짐 명령-> 0xf7, 0x0b, 0x01, 0x19, 0x02, 0x40, 0x22, 0x01, 0x00, 0x85, 0xee
  # 꺼짐 명령-> 0xf7, 0x0b, 0x01, 0x19, 0x02, 0x40, 0x22, 0x02, 0x00, 0x86, 0xee
  - platform: rs485
    name: "Livingroom Light 2"
    device: [0xB0, 0x79, 0x21]
#    sub_device:
#      offset: 2
#      data: [0x21]
    state_on:
      offset: 3
      data: [0x02]
      and_operator: True
      inverted : False
    state_off:
      offset: 3
      data: [0x02]
      and_operator: True
      inverted : True
    command_on:
      data: [0xAC, 0x7A, 0x02, 0x01]#, 0x55]
      ack: [0xB0, 0x7A, 0x02, 0x01]#, 0x49]
    command_off:
      data: [0xAC, 0x7A, 0x02, 0x00]#, 0x54]
      ack: [0xB0, 0x7A, 0x02, 0x00]#, 0x48]
